name: npm auto linter

on: 
  push:
    branches: 
      master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run fix-lint
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: ${{ github.head_ref }}
          title: '[Auto Lint] Lint PR'
          commit-message: Lint commit
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: |
            All lints were auto-fixable
          labels: |
            automated-pr
